# Generated by Django 3.1.2 on 2020-10-26 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Strongly Disagree', 1), ('Disagree', 2), ('Neutral', 3), ('Agree', 4), ('Strongly Agree', 5)], max_length=100)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality.question')),
            ],
        ),
    ]
