# Generated by Django 3.1.2 on 2020-10-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('personality', '0002_auto_20201026_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user'),
        ),
    ]
