# Generated by Django 3.1.2 on 2020-10-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0004_auto_20201026_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questionId',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='userId',
            new_name='user',
        ),
    ]
